### PR TITLE
Add shebang to main.py

### PR DESCRIPTION
**Pull request by Half-Shot**
Makes my life easier, no harm in it eh ;)

### CODE REVIEW

**Comment by SShrike** [comment]
*Psst*, heard of `pip install -e .`?

**Comment by SShrike** [comment]
Also, if you're going to have a shebang, why not make it `/usr/bin/env python`, support for Python 2 and 3 is targeted.

**Comment by Half-Shot** [comment]
>*Psst*, heard of `pip install -e .`?

I had not. Interesting. Still would rather have the shebang since I can do ./main.py and be lazy.

>Also, if you're going to have a shebang, why not make it /usr/bin/env python

*shrug* Fine by me.

**Comment by SShrike** [comment]
Yeah my workflow is like so:
```
virtualenv .env
source .env/bin/activate.fish
pip install -e .[dev, test]
```

**Pull request merged**
